### ISSUE TITLE
Investigate non-linked nodes in graph 

### ISSUE THREAD

**Issue by Shastick** [Shastick/orgarec#10]
Are there really 0 co-students or is it a bug ?

**Comment by ChrisJamesC** [comment]
In StudyPlanCompleteGraph.scala, there is a filter applied to links, if the distance is too high, the link is discarded.

**Comment by ChrisJamesC** [comment]
Well, even with 100% of links shown a lot of courses have 0 co-students. However, it is possible since it seems that they are bachelor courses and we are in the context of master in the actual visualisation.
